### PR TITLE
Macos v2

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Updated version of https://github.com/ocurrent/obuilder/pull/87
Used in https://github.com/ocurrent/ocluster/pull/193

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
The GH Actions test runs out of disk space, need to split that into smaller tests or cleanup disk space during the test.

**Comment by MisterDA** [comment]
I was a bit confused by the "scoreboard" name for the map of usernames to ids.

**Comment by tmcgilchrist** [comment]
Not sure what the history of that naming is and why it needs to be symlinks in the filesystem rather than user_id to home directory mapping. @patricoferris

**Comment by tmcgilchrist** [comment]
I am going to merge this as is and address follow up issues in subsequent PRs.
This has been running on the cluster for a few months now and is reasonably stable.

**Pull request merged**
