### PR TITLE
Remove `delete_recursively`

### PR DESCRIPTION
**Pull request by shonfeder**
Looks like this was copied from Lwt at some point. It is not used within obuilder currently, nor have I found it used in any of our other projects. And it has since been exposed in Lwt. See https://github.com/ocsigen/lwt/blob/48abed72467ca7479e95f1be06d02f40c7c434bd/CHANGES#L25

### CODE REVIEW

**Review by punchagan — APPROVED** [review]
Nice! Thanks for taking care of this. 

From the placement of the comment, it looks like the `win32_unlink` and `unlink` may also be artifacts of the `delete_recursively` function. I took a quick look and didn't find uses of this `unlink` function too. If it's not being used anywhere, could those go too?

**Comment by MisterDA** [comment]
I confirm that all these functions can be removed now that they've been exposed from Lwt.

**Comment by shonfeder** [comment]
Thank you for the reviews (and for spotting the extra dead code, @punchagan)!

**Review by MisterDA — APPROVED** [review]

**Comment by shonfeder** [comment]
The CI errors are spurious, and recorded in issues.

**Pull request merged**
