### PR TITLE
Add upper bound on tar-unix 3

### PR DESCRIPTION
**Pull request by shonfeder**
Corresponding to https://github.com/ocaml/opam-repository/pull/26331

### CODE REVIEW

**Comment by shonfeder** [comment]
Tracking issue for followup to update to the new api: https://github.com/ocurrent/obuilder/issues/185

**Review by punchagan — APPROVED** [review]
Thanks for taking care of this!

**Comment by shonfeder** [comment]
From the lower bounds check:

```
ASSERT Final result
[failure] Could not close database! It is busy.
          Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
          Called from Obuilder__Build.Make.finish in file "lib/build.ml", line 327, characters 4-24
          Called from Lwt.Sequential_composition.finalize.(fun) in file "src/core/lwt.ml", line 2251, characters 21-28
          Called from Lwt.Sequential_composition.try_bind.create_result_promise_and_callback_if_deferred.callback in file "src/core/lwt.ml", line 2132, characters 23-27
```

From debian 12 and 2 fedora instances:

```
test.exe: [INFO] b1: "(from base)"
test.exe: [INFO] Base image not present; importing "base"…
test.exe: [INFO] Exec "sudo" "--" "mkdir" "-m" "755" "--" "/tmp/build_e7f718_dune/mock-store-320eb3/cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2-tmp/rootfs"
exec: [|sudo; --; mkdir; -m; 755; --;
        /tmp/build_e7f718_dune/mock-store-320eb3/cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2-tmp/rootfs|]
test.exe: [INFO] Exec "docker" "create" "--" "base"
exec: [|docker; create; --; base|]
test.exe: [INFO] Exec "docker" "export" "--" "base-7"
exec: [|docker; export; --; base-7|]
test.exe: [INFO] Exec "sudo" "--" "tar" "-C" "/tmp/build_e7f718_dune/mock-store-320eb3/cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2-tmp/rootfs" "-xf" "-"
exec: [|sudo; --; tar; -C;
        /tmp/build_e7f718_dune/mock-store-320eb3/cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2-tmp/rootfs;
        -xf; -|]
test.exe: [INFO] Exec "docker" "rm" "--force" "--" "base-7"
exec: [|docker; rm; --force; --; base-7|]
docker rm --force "base-7"
test.exe: [INFO] Exec "docker" "image" "inspect" "--format" "{{range .Config.Env}}{{print . "\x00"}}{{end}}" "--" "base"
exec: [|docker; image; inspect; --format;
        {{range .Config.Env}}{{print . "\x00"}}{{end}}; --; base|]
test.exe: [INFO] b1: "---> saved as \"cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2\""
test.exe: [INFO] b1: "/: (run (shell Wait))"
test.exe: [INFO] b1: "Wait\n"
test.exe: [INFO] b2: "(from base)"
test.exe: [INFO] b2: "---> using \"cae662172fd450bb0cd710a769079c05bfc5d8e35efa6576edc7d0377afdd4a2\" from cache"
test.exe: [INFO] b2: "/: (run (shell Wait))"
test.exe: [INFO] b2: "Wait\n"
test.exe: [INFO] User cancelled job (users now = 1)
ASSERT User 1 result
test.exe: [INFO] User cancelled job (users now = 0)
ASSERT User 2 result
ASSERT Build cancelled
[exception] Unix.Unix_error(Unix.ENOENT, "lstat", "/tmp/build_e7f718_dune/mock-store-320eb3/state/db/db.sqlite-shm")
            Raised by primitive operation at Lwt_unix.self_result in file "src/unix/lwt_unix.cppo.ml", line 246, characters 14-31
```

**Comment by shonfeder** [comment]
Parts of the CI have been broken here at least since https://github.com/ocurrent/obuilder/commit/12373f18f42fc796638061fdfba31536e25c776f but these failures seem new, and maybe a problem in the infrastructure itself?

**Comment by shonfeder** [comment]
Apparently those were transient failures.

**Pull request merged**
